DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;

CREATE TABLE customers
(
    id      INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1000 INCREMENT BY 1),
    name    VARCHAR(80),
    address VARCHAR(80)
);


INSERT INTO customers (id, name, address)
VALUES (1, 'Klaus', 'Mainstreet 123');
INSERT INTO customers (id, name, address)
VALUES (2, 'Susi', 'Mainroad 76');

CREATE TABLE orders
(
    id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1000 INCREMENT BY 1),
    customer_id INTEGER NOT NULL REFERENCES customers (id),
    discount    INTEGER
);

CREATE TABLE order_items
(
    id       INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1000 INCREMENT BY 1),
    order_id INTEGER NOT NULL REFERENCES orders (id),
    product  VARCHAR NOT NULL,
    quantity INTEGER NOT NULL,
    price    NUMERIC(15, 2) NOT NULL
);

insert into orders (id, customer_id, discount)
VALUES (1, 1, 0);
insert into order_items (id, order_id, product, quantity, price)
VALUES (1, 1, 'Pants', 1, 99.49);
insert into order_items (id, order_id, product, quantity, price)
VALUES (2, 1, 'Shirt', 1, 75);

insert into orders (id, customer_id, discount)
VALUES (2, 2, 10);
insert into order_items (id, order_id, product, quantity, price)
VALUES (20, 2, 'Beer', 6, 18);
insert into order_items (id, order_id, product, quantity, price)
VALUES (21, 2, 'Wine', 1, 24.50);

